# Generated by Django 5.2.2 on 2025-06-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=100, verbose_name='Профессия')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
