# Generated by Django 5.2.2 on 2025-06-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта')),
                ('employer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Работодатель')),
                ('url', models.URLField(verbose_name='Ссылка на вакансию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.DeleteModel(
            name='JobSearch',
        ),
    ]
