# Generated by Django 5.2.2 on 2025-06-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_vacancy_delete_jobsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='query',
            field=models.CharField(default='Нет данных', max_length=255, verbose_name='Исходный запрос'),
        ),
    ]
