# Generated by Django 5.2.2 on 2025-06-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancy_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='benefits',
            field=models.TextField(blank=True, null=True, verbose_name='Неденежные бенефиты'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Внутренняя вакансия'),
        ),
    ]
