# Generated by Django 5.2.2 on 2025-06-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_vacancy_benefits_vacancy_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='user_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
